# Defines our composer file version
version: "3.1"
# Define our services 
services: 
  # This is our nodejs app built using the Dockerfile
  app:
    # The name of our node app container
    container_name: docker-prueba
    # Restarts our node app whenever it fails
    restart: always
    # Builds the node app docker container from the local -
    # Docker file we created
    build: .
    # Exposes the necessary ports that our node app uses
    ports:
      - "5000:5000"
    # All the services our node app will link to -
    # which in our case is only mongo
    # You can other services such as a Redis
    links:
      # The name should be similar to the service you will build
      - mongo
  # Our database service called mongo
  mongo:
    # The name of the database container, NOTE: it is similar to the name provided
    # in the links value
    container_name: mongo
    command: mongod
    volumes:
      - ./myData:/data/db
    # Builds a mongo image from the docker repository
    image: mongo
    # Exposes the ports that mongo uses
    ports:
      - "27017:27017"